name = "groom"

[task.build]
description = "Build the project"
command = 'go build .'
environment = [ "CGO_ENABLED=0" ]
depends = [
    "format",
]

[task.format]
description = "Format the project"
command = "go fmt ./..."

[task.gifs]
description = "Generate gifs"
directory = "gifs"
shell = "bash"
command = 'find . -type f -name "*.tape" -exec vhs {} \;'
