name = "groom"

[variables]
version = "0.1.0"
build-dir = "build"
main-file = "main.go"
ldflags = "-X main.VERSION='$version'"

[task.build]
description = "Build the project"
command = 'go build -ldflags "$ldflags" -o $name ${main-file}'
environment = [ "CGO_ENABLED=0" ]
depends = [
    "format"
]

[task.format]
description = "Format the project"
command = "go fmt ./..."


[task.clean]
description = "Clean the repository"
command = "rm -rf ${build-dir}"

[task.install]
description = "Install the binary(Requires gox)"
command = "gox install ."

